spring:
  #  datasource:
  #    master:
  #      driver-class-name: com.mysql.jdbc.Driver
  #      url: jdbc:mysql://localhost:3306/script-adaptor?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  #      username: root
  #      password: 123456
  profiles:
    active: druid
server:
  port: 8080

#logging:
#  level:
#    root: warn
#    com.zfm.com.zfm.scriptadaptor.infra.mapper: trace
#  pattern:
#    console: '%p%m%n'
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml
    - classpath*:/mapper/*/*Mapper.xml
  typeAliasesPackage: com.zfm.scriptadaptor.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: ${MYBATIS_DEFAULT_STATEMENT_TIMEOUT:120}
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0